version: '3.2'
services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        extra_hosts:
            - name_for_server:172.17.0.1
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 127.0.0.1:9090:9090
        restart: always
        
    alertmanager:
      image: prom/alertmanager
      container_name: alertmanager
      ports:
        - 127.0.0.1:9093:9093
      user: 'root'
      volumes:
        - ./alertmanager/:/etc/alertmanager/
      restart: always
      command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/etc/alertmanager/data'

    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        network_mode: host
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        restart: always

    cadvisor:
      image: gcr.io/google-containers/cadvisor
      container_name: cadvisor
      ports:
      - 8080:8080
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker:/var/lib/docker:ro
        - /cgroup:/cgroup:ro
      restart: unless-stopped

    grafana:
        image: grafana/grafana
        container_name: grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        user: 'root'
        volumes:
            - ./grafana:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        restart: always
