rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
      
scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['name_for_server:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']
